### ISSUE TITLE
TypeError: Cannot read property 'at' of undefined 

### ISSUE THREAD

**Issue by krauzac** [knuckleheadsmiff/homebridge-garagedoor-ryobi#14] opened 2021-04-14 17:47 UTC
Getting this error after updating to Homebridge 1.3.4, so I downgraded to 1.2.5 to fix for now.
Node.js Version  v14.16.1
Npm Version v7.9.0

Any Ideas? 

[14/04/2021, 13:06:26] [Prius] Error update 1 - retrieving ryobi GDO status
[14/04/2021, 13:06:27] [Prius] Error Message: TypeError: Cannot read property 'at' of undefined
[14/04/2021, 13:06:28] [Highlander] Error update 1 - retrieving ryobi GDO status
[14/04/2021, 13:06:28] [Highlander] Error Message: TypeError: Cannot read property 'at' of undefined

Config is :
 {
            "accessory": "RyobiGarageCommand",
            "name": "Prius",
            "email": "xxxxxxx@gmail.com",
            "password": "xxxxxxx",
            "garagedoor_name": "His",
            "poll_short_delay": "15",
            "poll_long_delay": "90",
            "serial_number": "001"
        },
        {
            "accessory": "RyobiGarageCommand",
            "name": "Highlander",
            "email": "xxxxxxx@gmail.com",
            "password": "xxxxxxx",
            "garagedoor_name": "Hers",
            "poll_short_delay": "15",
            "poll_long_delay": "90",
            "serial_number": "002"
        }

**Comment by knuckleheadsmiff** [comment] 2021-04-14 18:34
I can't reproduce this. I just upgraded to the latest version of homebridge 1.3.4 (and the latest version of homebridge UI) and it starts up cleanly and gets my garage door status without issue.

**Comment by krauzac** [comment] 2021-04-14 20:35
OK,  It may have to do with having two openers, I'll keep trying. - Thx

**Comment by knuckleheadsmiff** [comment] 2021-04-14 20:54
I see where the code is failing (its on one of these lines all near each other):

		const garageDoorModule = Object.values(values.result[0].deviceTypeMap)
			.find(function(m) {
				return m && m.at && m.at.moduleProfiles && m.at.moduleProfiles.value && m.at.moduleProfiles.value.some(function(v) {
					return v.indexOf('garageDoor_') === 0;
				});
			});

		this.doorPortId = garageDoorModule.at.portId.value;
		this.doorModuleId = garageDoorModule.at.moduleId.value;
		var doorval = values.result[0].deviceTypeMap['garageDoor_' + this.doorPortId].at.doorState.value

If you turn on the "debug_sensitive" property we can look at what was returned from ryobi to see why it could not parse the values but it would be odd that the same code is not working on two different versions or homebridge. Now what is particularly odd is that that the 'at' property is something I was not aware existed. This code was explicitly modified to support multiple doors when the 'at' property was access by @andyedinborough and he might be able to help look into this more. It is possible that not all javascript engines support this property (back in the day when I programmed JS professionally this property did not exist.)

**Comment by knuckleheadsmiff** [comment] 2021-04-14 21:04
I've invited @andyedinborough as a project member and will assign to him if he accepts.

**Comment by krauzac** [comment] 2021-04-14 21:49
Ran Andy's Tip of 
https://tti.tiwiconnect.com/api/devices?username=RYOBI_ACCOUNT_EMAIL&password=RYOBI_PASSORD

Grabbed my two garagedoor_id's from the JSON result and entered them in my config, replacing the garagedoor_name with garagedoor_id
That fix the 'at' of undefined error.
Back in business with latest HB 1.3.4!

**Comment by knuckleheadsmiff** [comment] 2021-04-14 21:52
It's odd that it still worked on one version but not the other? Oh well.

**Comment by andyedinborough** [comment] 2021-04-14 22:05
I can take a look at this. I'm guessing that the JSON data returned from the API has changed.

**Comment by knuckleheadsmiff** [comment] 2021-04-14 22:07
thanks, although this does not make sense since he says it works if he did not use the latest version of homebridge?

**Comment by krauzac** [comment] 2021-04-14 22:09
Spoke to soon, Home app looks happy, reports the doors closed. Trying to open just reports opening... then back to closed status.

**Comment by knuckleheadsmiff** [comment] 2021-04-14 22:12
Working for me; I just tested it. I only have a single door.

**Comment by krauzac** [comment] 2021-04-25 15:56
Thanks you Andy and KnuckleHead ! I have a Happy Wife again!

**Closed as completed** 2021-04-25 18:04 UTC
